# Generated by Django 5.2.1 on 2025-05-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0002_rename_bloco_unit_bloc_rename_numero_unit_number'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidade', to='condominium.unit'),
        ),
    ]
