# Generated by Django 5.2.1 on 2025-05-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_user_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
