# Generated by Django 5.2.1 on 2025-05-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='bloco',
            new_name='bloc',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='numero',
            new_name='number',
        ),
    ]
